Disable FUSE wrapper for ioctl() on OpenBSD
OpenBSD has it's own FUSE implementation that
doesn't support ioctl() operation.

In file included from /home/sergeyb/source/unreliablefs/unreliablefs.c:10:
/home/sergeyb/source/unreliablefs/unreliablefs_ops.h:55:47: warning: declaration of 'struct fuse_bufvec' will not be visible outside of this
      function [-Wvisibility]
int unreliable_write_buf(const char *, struct fuse_bufvec *buf, off_t off,
                                              ^
/home/sergeyb/source/unreliablefs/unreliablefs_ops.h:57:46: warning: declaration of 'struct fuse_bufvec' will not be visible outside of this
      function [-Wvisibility]
int unreliable_read_buf(const char *, struct fuse_bufvec **bufp,
                                             ^
/home/sergeyb/source/unreliablefs/unreliablefs.c:51:6: error: field designator 'ioctl' does not refer to any field in type
      'struct fuse_operations'
    .ioctl       = unreliable_ioctl,
     ^
2 warnings and 1 error generated.

Disable ioctl() enabled in commit c96dbe41b2f53fb5a9ac1e0fc798775c9cd01596
("Use check_function_exists() to detect functions support").